### ISSUE TITLE
Even after commit "Fix #480" getting "size mismatch for FC_layer.0.0.weight..." with forward script

### ISSUE THREAD

**Issue by OliverColeman** [torch-points3d/torch-points3d#546]
Posted the below in https://github.com/nicolas-chaulet/torch-points3d/issues/480 but figured I should open a new issue seeing as that one is closed.

I'm still getting the error reported by @christianlandgraf (`size mismatch for FC_layer.0.0.weight: copying a param with shape torch.Size([128, 129, 1]) from checkpoint, the shape in current model is torch.Size([128, 130, 1]).`)

I have the latest code (I checked it includes the commit "Fix # 480"). I also tried the workaround posted by @WeixiaoGao but it made no difference.

The train and forward scripts were run as listed in the README. My forward config.yaml is:
```
num_workers: 2
batch_size: 16
cuda: 0
weight_name: "miou" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/workspace/code/torch-points3d/outputs/benchmark/benchmark-pointnet2_charlesssg-20210202_102042" # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: pointnet2_charlesssg
enable_dropout: False
output_path: "/workspace/code/torch-points3d/outputs/benchmark/inf1" # Where the output goes
input_path: "/workspace/code/torch-points3d/data/shapenet/raw/02954340" # Folder where to find the data

# Dataset specific
defaults:
    - dataset: ""
      optional: True
```
