### ISSUE TITLE
Blank display when visualizing output results of KPConv model trained on scannet dataset 

### ISSUE THREAD

**Issue by RMalikM** [torch-points3d/torch-points3d#565]
It is in the follow up on the issue #561.
I trained KPConv model on Scannet dataset. The details are as follows:

**Command**
`python train.py task=segmentation model_type=kpconv model_name=KPDeformableConvPaper dataset=scannet training=kpconv visualization.activate=True`

**kpconv.yaml**

```
# Those arguments defines the training hyper-parameters
training:
    epochs: 300
    num_workers: 2
    batch_size: 4
    cuda: 0
    precompute_multi_scale: True # Compute multiscate features on cpu for faster training / inference
    optim:
        base_lr: 0.01
        grad_clip: 100
        optimizer:
            class: SGD
            params:
                momentum: 0.9
                lr: ${training.optim.base_lr} # The path is cut from training
                weight_decay: 1e-4
                dampening: 0.1
        lr_scheduler: ${lr_scheduler}
        bn_scheduler:
            bn_policy: "step_decay"
            params:
                bn_momentum: 0.1
                bn_decay: 0.9
                decay_step: 20
                bn_clip: 1e-2
    weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
    enable_cudnn: True
    checkpoint_dir: ""

# Those arguments within experiment defines which model, dataset and task to be created for benchmarking
# parameters for Weights and Biases
wandb:
    entity: photogauge
    project: scannet-benchmark
    log: True
    notes: "KPConv benchmark training"
    name: "kpconv"
    public: True # It will be display the model within wandb log, else not.

# parameters for TensorBoard Visualization
tensorboard:
    log: False
```

**Env**
```
absl-py==0.11.0
anyio==2.2.0
appdirs==1.4.4
argon2-cffi==20.1.0
ase==3.21.1
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
bleach==3.3.0
bokeh==2.3.0
cached-property==1.5.2
cachetools==4.2.1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==7.1.2
configparser==5.0.1
contextvars==2.4
cycler==0.10.0
dataclasses==0.6
decorator==4.4.2
defusedxml==0.6.0
docker-pycreds==0.4.0
entrypoints==0.3
filelock==3.0.12
future==0.18.2
gdown==3.12.2
gitdb==4.0.5
GitPython==3.1.13
google-auth==1.27.0
google-auth-oauthlib==0.4.2
googledrivedownloader==0.4
gql==0.2.0
graphql-core==1.1
grpcio==1.35.0
h5py==3.1.0
hydra-core==0.11.3
idna==2.10
imageio==2.9.0
immutables==0.15
importlib-metadata==3.4.0
ipykernel==5.4.3
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
isodate==0.6.0
jedi==0.18.0
Jinja2==2.11.3
joblib==1.0.1
json5==0.9.5
jsonpatch==1.28
jsonpointer==2.0
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-core==4.7.1
jupyter-packaging==0.7.12
jupyter-server==1.4.1
jupyterlab==3.0.9
jupyterlab-pygments==0.1.2
jupyterlab-server==2.3.0
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
llvmlite==0.33.0
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.3.4
meshio==4.3.10
mistune==0.8.4
nbclassic==0.2.6
nbclient==0.5.2
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
networkx==2.5
notebook==6.2.0
numba==0.50.1
numpy==1.19.5
nvidia-ml-py3==7.352.0
oauthlib==3.1.0
omegaconf==1.4.1
open3d==0.10.0.0
packaging==20.9
pandas==1.1.5
pandocfilters==1.4.3
panel==0.11.0
param==1.10.1
parso==0.8.1
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.0
pkg-resources==0.0.0
plyfile==0.7.3
prometheus-client==0.9.0
promise==2.3
prompt-toolkit==3.0.16
protobuf==3.14.0
psutil==5.8.0
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyct==0.4.8
Pygments==2.8.0
pyparsing==2.4.7
pyrsistent==0.17.3
PySocks==1.7.1
python-dateutil==2.8.1
python-louvain==0.15
pytorch-metric-learning==0.9.97.dev2
pytz==2021.1
pyvista==0.28.1
pyviz-comms==2.0.1
PyWavelets==1.1.1
PyYAML==5.4.1
pyzmq==22.0.3
rdflib==5.0.0
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.1
scikit-image==0.16.2
scikit-learn==0.24.1
scipy==1.5.4
scooby==0.5.6
Send2Trash==1.5.0
sentry-sdk==0.20.2
shortuuid==1.0.1
six==1.15.0
smmap==3.0.5
sniffio==1.2.0
subprocess32==3.5.4
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
terminado==0.9.2
testpath==0.4.4
threadpoolctl==2.1.0
torch==1.7.0
torch-cluster==1.5.8
torch-geometric==1.6.3
torch-points-kernels==0.6.10
torch-scatter==2.0.5
torch-sparse==0.6.8
torchfile==0.1.0
torchnet==0.0.4
torchvision==0.8.1
tornado==6.1
tqdm==4.57.0
traitlets==4.3.3
transforms3d==0.3.1
typing-extensions==3.7.4.3
urllib3==1.26.3
visdom==0.1.8.9
vtk==9.0.1
wandb==0.8.36
watchdog==2.0.1
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
zipp==3.4.0

```

**Machine details**
Ubuntu 18.04.5 LTS
Memory: 47GB
GPU: NVIDIA Corporation (GeForce RTX 2080Ti)

**Issue**

The training was completed successfully and it generated `.ply` files (for visualization)  in `viz` folder for each epoch corresponding to train and val splits. Then, I tried `notebooks/dashboard.ipynb` to visualize the results. Notebook runs without any error but there is nothing in the display window. It is blank as shown in the following snapshot:

![Capture](https://user-images.githubusercontent.com/53081324/111286157-ecf27c00-8667-11eb-8857-e58a659080b6.PNG)

**Additional info**
1. Here is one of the output `.ply` files:
[102_3.zip](https://github.com/nicolas-chaulet/torch-points3d/files/6147637/102_3.zip)

2. Generated graphs during the training:

![image](https://user-images.githubusercontent.com/53081324/111294159-0992b200-8670-11eb-8a05-fd01d177f6a6.png)

It looks like there are no points in these point clouds. Is it a bug or am I missing something here? 
Kindly help.

@CCInc @nicolas-chaulet
