### ISSUE TITLE
Where to find tensorboard output for visualization?

### ISSUE THREAD

**Issue by juanmed** [torch-points3d/torch-points3d#637]
Hi,

Let me first thank you and all contributors for developing such a great framework. After much reading and digging, I was able to create a custom loader for my data and train pointnet++ with it, but now I am trying to visualize the training curves with tensorboard and was unsuccessful. 

My train configuration is as below, with tensorboard log enabled (I assume) but I am unable to find a tensorboard output folder or file. I thought that running  ```tensorboard --logdir output/date_of_today/time_of_train/``` would allow me to visualize the training session but it does not work.

Any help on how to visualize the training curves (loss, miou, acc vs epoch) will be appreciated :)

Thanks

```yaml
training:
    epochs: 100
    num_workers: 6
    batch_size: 16
    shuffle: True
    cuda: 0
    precompute_multi_scale: False
    optim:
        base_lr: 0.001
        accumulated_gradient: 2
        grad_clip: -1
        optimizer:
            class: Adam
            params:
                lr: 0.001
        lr_scheduler:
            class: MultiStepLR
            params:
                milestones: [10, 25, 50, 75, 100]
                gamma: 0.1
        bn_scheduler:
            bn_policy: "step_decay"
            params:
                bn_momentum: 0.1
                bn_decay: 0.9
                decay_step : 1024
                bn_clip : 1e-2
    weight_name: "latest"
    enable_cudnn: True
    checkpoint_dir: ""
    resume: True

wandb:
    project: default
    log: False
    notes: ""
    name: ""
    public: True

tensorboard:
    log: True

```
